jobs:
  - name: storage-production-all
    max_in_flight: 1
    plan:
      - in_parallel:
        - put: meta
          resource: meta-production
        - get: dataworks-corporate-storage-coalescence
          trigger: false
        - get: aws-ingestion
          trigger: false
        - get: aws-internal-compute
          trigger: false
        - get: dataworks-aws-ingest-consumers
          trigger: false

      - .: (( inject meta-corporate-storage-coalescer.plan.terraform-bootstrap ))

      - in_parallel:
        - .: (( inject meta-corporate-storage-coalescer.plan.terraform-output-ingest ))
          config:
            params:
              TF_WORKSPACE: production
        - .: (( inject meta-corporate-storage-coalescer.plan.terraform-output-internal-compute ))
          config:
            params:
              TF_WORKSPACE: production
        - .: (( inject meta-corporate-storage-coalescer.plan.terraform-output-ingest-consumers ))
          config:
            params:
              TF_WORKSPACE: production

      - in_parallel:
        - .: (( inject meta-corporate-storage-coalescer.plan.set-coalescer-parameters-all-partitions-main ))
          attempts: 3
          config:
            params:
              AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
              FILE_TYPE: "storage"
              THREAD_COUNT: 10
        - .: (( inject meta-corporate-storage-coalescer.plan.set-coalescer-parameters-all-partitions-audit ))
          attempts: 3
          config:
            params:
              AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
              FILE_TYPE: "storage"
              THREAD_COUNT: 10
        - .: (( inject meta-corporate-storage-coalescer.plan.set-coalescer-parameters-all-partitions-equalities ))
          attempts: 3
          config:
            params:
              AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
              FILE_TYPE: "storage"
              THREAD_COUNT: 1

      - in_parallel:
        - .: (( inject meta-corporate-storage-coalescer.plan.run-coalescer-all-partitions-main ))
          config:
            params:
              AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
              FILE_TYPE: "storage"
        - .: (( inject meta-corporate-storage-coalescer.plan.run-coalescer-all-partitions-audit ))
          config:
            params:
              AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
              FILE_TYPE: "storage"
        - .: (( inject meta-corporate-storage-coalescer.plan.run-coalescer-all-partitions-equalities ))
          config:
            params:
              AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
              FILE_TYPE: "storage"
